apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyIxOTIuMTY4LjUwLjEwOjUwMDAiOnsidXNlcm5hbWUiOiJtb2hpdCIsInBhc3N3b3JkIjoiTmV3ZGVsaGlAMTMiLCJhdXRoIjoiYlc5b2FYUTZUbVYzWkdWc2FHbEFNVE09In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: testing
  namespace: demo-webapp
type: kubernetes.io/dockerconfigjson
