apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - helm-release.yaml
configMapGenerator:
  - name: stage-values
    files:
      - values.yaml=mysqlvalues.yaml
configurations:
  - kustomizeconfig.yaml
